### ISSUE TITLE
Doesn't follow RESTful conventions

### ISSUE THREAD

**Issue by jmpann** [learn-co-curriculum/cookies_and_sessions_lab#14]
Tests don't explicitly test for RESTful conventions.

**Comment by DanielSeehausen** [comment]
hey @jmpann thanks for the issue being raised! We would love to fix this -- could you possibly provide us with more information (where/why) and we will get on it!

**Comment by DanielSeehausen** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
