### ISSUE TITLE
Breaks if you don't name your variable 'cart'

### ISSUE THREAD

**Issue by storywr** [learn-co-curriculum/cookies_and_sessions_lab#16]
require 'rails_helper'

RSpec.describe "products/index", :type => :view do
  it "shows everything in the **cart**" do
    assign(:cart, ['apples', 'bananas', 'pears'])
    render
    expect(rendered).to include 'apples'
    expect(rendered).to include 'bananas'
    expect(rendered).to include 'pears'
  end

if you name your variable anything other than 'cart' it won't work. very annoying unless you read the spec closely

**Comment by gj** [comment]
Fixed in #12 — sorry about that @storywr !
