### ISSUE TITLE
Might need to add web-console to gemfile

### ISSUE THREAD

**Issue by breadoliveoilsalt** [learn-co-curriculum/cookies_and_sessions_lab#19]
Hi.  In case helpful:

- After cloning the lesson and while working in my own environment, I kept getting the following error whenever I ran rspec out of the gate:

`NoMethodError:
  undefined method 'web_console' for #<Rails::Application::Configuration:0x007fe5511984b0>
  Did you mean?  console`

(The whole error is reproduced below. My ruby version is: 2.3.1p112.  I did not try any of this out in the learn ide.)

- Running `bundle update` and/or `bundle exec rspec` did not help.  What solved the issue was adding this to the gemfile:

`gem 'web-console', '~> 2.0'`

That cleared everything up. 

Thanks!

-----
Here's the whole error:

```
NoMethodError:
  undefined method `web_console' for #<Rails::Application::Configuration:0x007fe5511984b0>
  Did you mean?  console
# /Users/adistinti/.rvm/gems/ruby-2.3.1/gems/railties-4.2.10/lib/rails/railtie/configuration.rb:95:in `method_missing'
# ./config/application.rb:11:in `<class:Application>'
# ./config/application.rb:10:in `<module:CookiesAndSessionsLab>'
# ./config/application.rb:9:in `<top (required)>'
# ./config/environment.rb:2:in `require'
# ./config/environment.rb:2:in `<top (required)>'
# ./spec/rails_helper.rb:3:in `require'
# ./spec/rails_helper.rb:3:in `<top (required)>'
# ./spec/controllers/application_controller_spec.rb:1:in `require'
# ./spec/controllers/application_controller_spec.rb:1:in `<top (required)>'

```

**Comment by DanielSeehausen** [comment]
fixed! thanks
