### ISSUE TITLE
Typo in Products/index test

### ISSUE THREAD

**Issue by dwyn** [learn-co-curriculum/cookies_and_sessions_lab#20]
Please replace  `session[:cart] = ['apples', 'bananas', 'pears']` 
with `assign(:cart, ['apples', 'bananas', 'pears'])`

**Comment by d-d-d-dalia** [comment]
Changed it back to `session[:cart] = ['apples', 'bananas', 'pears']` because cart was returning an empty array and so couldn't be iterated over. Reverting to original test code passed the specs.

**Comment by justinddaniel** [comment]
Seconded. I had another student on Screenshare and we had to revert back to session[:cart] = ['apples', 'bananas', 'pears']

**Comment by dapawn** [comment]
Third'ed, I had to change it to session[:cart] = ['apples', 'bananas', 'pears'], to pass the tests. Please chnage the test back.

**Comment by heavenlyboheme** [comment]
It looks as though the typo is changed and the issue resolved. session[:cart] = ['apples', 'bananas', 'pears']
