### ISSUE TITLE
Bugs Last 2 failure messages

### ISSUE THREAD

**Issue by rogerprz** [learn-co-curriculum/cookies_and_sessions_lab#22]
Unable to pass failure messages even with solution.

**Comment by cjbrock** [comment]
Hello @rogercodes1,
We haven't had any other reports of being unable to pass the final two tests, so it's possible that you're missing something in the lesson itself. Try using Ask A Question to get some help from a Technical Coach or one of the community members, and they should be able to point you in the right direction!

// <3 Corinna
