### ISSUE TITLE
Running learn throws Thor error

### ISSUE THREAD

**Issue by adamurbina** [learn-co-curriculum/cookies_and_sessions_lab#24]
Running learn command results in error:

/usr/local/rvm/gems/ruby-2.3.1/gems/thor-0.20.1/lib/thor/error.rb:12:in `<module:DidYouMean>': uninitialized constant Thor::DidYouMean::SpellChecker (NameError)

Not sure how to resolve the issue. Tried reinstalling gem, adding it to gem file etc...

**Comment by jenmyers** [comment]
Hi there,

This issue cannot be reproduced and could have been the result of an environment issue. Closing now.
