### ISSUE TITLE
Issue with Gem Bundler

### ISSUE THREAD

**Issue by joanapalero** [learn-co-curriculum/cookies_and_sessions_lab#25]
Hello I received this error when trying to run the lab:
`Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.3, >= 1.3.1)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.3, >= 1.3.1)' in any of the relevant sources:
  the local ruby installation`

**Comment by jenmyers** [comment]
Hi there,

This issue cannot be reproduced and could have been the result of an environment issue. Closing now.
