### ISSUE TITLE
Cart.rb test raises capybara errors

### ISSUE THREAD

**Issue by asherkory** [learn-co-curriculum/cookies_and_sessions_lab#3]
First tried to run the "feature/cart.rb" test, and had to rename the folder and file to "features/cart_spec.rb" so that the learn gem could find it properly.

Running the test yielded this capybara error:

`NoMethodError:
       undefined method`visit' for #RSpec::ExampleGroups::Homepage:0x007f9882f21008`

I added 
`require 'capybara/rails'
require 'capybara/rspec'`

to the rails_helper, which did not change the error. Some Stack Exchange answers suggested changing the type in the describe block to feature (previously :view), so I changed it to this line:

`RSpec.describe "homepage", :type => :feature do
`

Now the test progressed further! And raised this new error:

`Failure/Error: fill_in 'product', 'kumquats'

```
 RuntimeError:
   Must pass a hash containing 'with'`
```

So I changed the applicable line to `fill_in 'product', with: 'kumquats'`
Which produced a new error:
`Failure/Error: expect(page).to include 'kumquats'

```
   expected #<Capybara::Session> to include "kumquats", but it does not respond to `include?`
   Diff:
   @@ -1,2 +1,2 @@
   -["kumquats"]
   +#<Capybara::Session>`
```

Still trying to figure out how to get past this one.

**Comment by pletcher** [comment]
https://github.com/learn-co-curriculum/cookies_and_sessions_lab/commit/c1bde0bc3c169adb71ed3b259b7eda8b2d2828fa
